version: '2.0'

services:
  db:
    image: postgres
    # volumes:
    #   - /home/db:/var/lib/postgresql/data
    env_file: 
      - ./ENV.md

  web:
    build: .
    image: micropyramid/django-crm:1
    env_file: 
      - ./ENV.md
    ports:
      - "8001:8000"
    depends_on:
      - db